update

diff --git a/build_install_driver b/build_install_driver
--- a/build_install_driver
+++ b/build_install_driver
@@ -1,41 +1,15 @@
 #!/bin/bash -e
+. ./scripts/getoptions.sh
 
-function check_help {
-  case "$1" in
-  "--help" | "-h")
-    echo "************************************************************"
-    echo "*** HELP ***************************************************"
-    echo "************************************************************"
-    echo "*** Run the script without parameter to build and        ***"
-    echo "*** install the driver. The build script will creates a  ***"
-    echo "*** build directory (./tmp_build).                       ***"
-    echo "*** To specify a build directory just pass a directory   ***"
-    echo "*** path.                                                ***"
-    echo "***                                                      ***"
-    echo "*** e.g.:                                                ***"
-    echo "*** mkdir ./my_build_path                                ***"
-    echo "*** ./build_install_driver ./my_build_path               ***"
-    echo "************************************************************"
-    exit 0
-    ;;
-  *)
-  ;;
-  esac
+parser_definition() {
+    setup   REST help:usage -- "Usage: build_install_driver.sh [options]" ''
+    msg -- 'Options:'
+    param  BUILDDIR   -b --builddir                    init:="./tmp_build/"       -- "The build directory"
+    flag   YESALL     -y --yes       on:true of:false  init:=false                -- "Yes all"
+    flag   ENABLESPI  -s --spi       on:true of:false  init:=false                -- "Enable SPI"
+    disp    :usage    -h --help
 }
-
-
-builddir="./tmp_build/"
-if (( "$#" >= "1" )); then
-  check_help $1
-  if [ -d "${1}" ]; then
-    builddir=$(realpath "${1}")
-  else
-    echo "Error - Given parameter \"$1\" is not a folder or does not exist!"
-    exit 1
-  fi
-else
-  mkdir -p "${builddir}"
-fi
+eval "$(getoptions parser_definition) exit 1"
 
 # check if directories contain white spaces...
 invalid_path=$(pwd | { grep " " || true; } )
@@ -43,26 +17,32 @@ if [ "${invalid_path}" != "" ]; then
     echo "Error - path contains spaces (\"${PWD}\")! Please use path without."
     exit 1
 fi
-invalid_path=$(echo ${builddir} | { grep " " || true; } )
+invalid_path=$(echo ${BUILDDIR} | { grep " " || true; } )
 if [ "${invalid_path}" != "" ]; then
-    echo "Error - path contains spaces (\"${builddir}\")! Please use path without."
+    echo "Error - path contains spaces (\"${BUILDDIR}\")! Please use path without."
     exit 1
 fi
 
-if [ -d "${builddir}/libcifx" ] || [ -d "${builddir}/uio_netx" ]; then
-    echo "********************************************************************************"
-    echo "NOTE: The build folder (\"${builddir}\") is not empty! Force overwrting (yes=y)?"
-    echo "      Or pass a new build folder (./build_install_driver [my_build_folder]."
-    echo "********************************************************************************"
-    read delete_files
-    if [ "${delete_files}" = "y" ]; then
-	echo "...deleting build folder!"
-	rm -rf "${builddir}/libcifx"
-	rm -rf "${builddir}/uio_netx" 
-    else
-	echo "...canceled build process!"
-	exit 1
+if [ -d "${BUILDDIR}/libcifx" ] || [ -d "${BUILDDIR}/uio_netx" ]; then    
+    if "${YESALL}"; then
+      delete_files="y"
+    else  
+      echo "********************************************************************************"
+      echo "NOTE: The build folder (\"${BUILDDIR}\") is not empty! Force overwrting (yes=y)?"
+      echo "      Or pass a new build folder (./build_install_driver [my_build_folder]."
+      echo "********************************************************************************"
+      read delete_files
     fi
+    if [ "${delete_files}" = "y" ]; then
+      echo "...deleting build folder!"
+      rm -rf "${BUILDDIR}/libcifx"
+      rm -rf "${BUILDDIR}/uio_netx" 
+    else
+      echo "...canceled build process!"
+      exit 1
+    fi
+else
+  mkdir -p "${BUILDDIR}"
 fi
 
 driver_src=$(dirname $(realpath $0))
@@ -87,15 +67,15 @@ ret=1
 ;;
 uio_netx)
 install_step="firmware"
-mkdir -p "${builddir}/uio_netx"
+mkdir -p "${BUILDDIR}/uio_netx"
 echo "************************************************************"
 echo "**** Start building kernel module uio_netx               ***"
 echo "************************************************************"
-if ! "${scripts_dir}/"install_uio_netx build "${builddir}/uio_netx"; then  # build module
+if ! "${scripts_dir}/"install_uio_netx build "${BUILDDIR}/uio_netx" ${YESALL}; then    # build module
   echo "Error building kernel module!"
   install_step="error"
 fi
-if ! "${scripts_dir}/"install_uio_netx install "${builddir}/uio_netx"; then          # install module
+if ! "${scripts_dir}/"install_uio_netx install "${BUILDDIR}/uio_netx" ${YESALL}; then  # install module
   echo "Error installing kernel module!"
   install_step="error"
 fi
@@ -106,19 +86,19 @@ echo "************************************************************"
 echo "**** Installing kernel module and firmware               ***"
 echo "************************************************************"
 install_step="libcifx"
-if ! "${scripts_dir}/"install_firmware install ; then        # install firmware
+if ! "${scripts_dir}/"install_firmware install ${YESALL}; then        # install firmware
   echo "Error installing firmware!"
   install_step="error"
 fi
-if ! "${scripts_dir}/"install_uio_netx update ; then         # load driver
+if ! "${scripts_dir}/"install_uio_netx update ${YESALL}; then         # load driver
   echo "Error updating module dependencies!"
   install_step="error"
 fi
-if ! "${scripts_dir}/"install_uio_netx unload ; then
+if ! "${scripts_dir}/"install_uio_netx unload ${YESALL}; then
   echo "Error unloading driver!"
   install_step="error"
 fi
-if ! "${scripts_dir}/"install_uio_netx load; then
+if ! "${scripts_dir}/"install_uio_netx load ${YESALL}; then
     echo "Error loading driver!"
     install_step="error"
 fi
@@ -127,8 +107,8 @@ libcifx)
 echo "************************************************************"
 echo "**** Building and installing user space library libcifx  ***"
 echo "************************************************************"
-mkdir -p "${builddir}/libcifx"
-"${scripts_dir}/"install_libcifx "${builddir}/libcifx"
+mkdir -p "${BUILDDIR}/libcifx"
+"${scripts_dir}/"install_libcifx "${BUILDDIR}/libcifx" ${YESALL} ${ENABLESPI}
 install_step="stop"
 ;;
 esac
diff --git a/scripts/install_libcifx b/scripts/install_libcifx
--- a/scripts/install_libcifx
+++ b/scripts/install_libcifx
@@ -1,4 +1,6 @@
 #!/bin/bash -e
+YESALL=${2:-false}
+ENABLESPI=${3:-false}
 
 drv_dir=$(dirname $(realpath $0))"/../libcifx/"
 buildfolder="${drv_dir}"
@@ -9,50 +11,68 @@ if (( "$#" >= "1" )); then
   fi
 fi
 
-  # build and install user space library
+# build and install user space library
+if "${YESALL}"; then
+  debug_enable="y"
+else  
   echo "To enable build of debug symbols type 'y' else 'n':"
   read debug_enable
-  if [ "$debug_enable" == "y" ]; then
-    options="$options -DDEBUG=ON"
-  else
-    options="$options -DDEBUG=OFF"
-  fi
+fi
+if [ "$debug_enable" == "y" ]; then
+  options="$options -DDEBUG=ON"
+else
+  options="$options -DDEBUG=OFF"
+fi
+if "${YESALL}"; then
+  debug_enable="y"
+else  
   echo "To enable dma support type 'y' else 'n':"
   echo "NOTE: This feature requires to build uio_netx also with dma support!"
   read debug_enable
-  if [ "$debug_enable" == "y" ]; then
-    options="$options -DDMA=ON"
-  else
-    options="$options -DDMA=OFF"
-  fi
+fi
+if [ "$debug_enable" == "y" ]; then
+  options="$options -DDMA=ON"
+else
+  options="$options -DDMA=OFF"
+fi
+if "${YESALL}"; then
+  ethernet_enable="y"
+else  
   echo "To enable ethernet support type 'y' else 'n':"
   echo "NOTE: This feature requires dedicated hardware and firmware!"
   read ethernet_enable
-  if [ "$ethernet_enable" == "y" ]; then
-    options="$options -DVIRTETH=ON"
-  else
-    options="$options -DVIRTETH=OFF"
-  fi
+fi
+if [ "$ethernet_enable" == "y" ]; then
+  options="$options -DVIRTETH=ON"
+else
+  options="$options -DVIRTETH=OFF"
+fi
+if "${ENABLESPI}"; then
+  spi_plugin_enable="y"
+elif "${YESALL}"; then
+  spi_plugin_enable="n"
+else
   echo "To enable SPI plugin support type 'y' else 'n':"
   read spi_plugin_enable
-  if [ "$spi_plugin_enable" == "y" ]; then
-    options="$options -DSPM_PLUGIN=ON"
+fi
+if [ "$spi_plugin_enable" == "y" ]; then
+  options="$options -DSPM_PLUGIN=ON"
+else
+  options="$options -DSPM_PLUGIN=OFF"
+fi
+tmp_dir=$pwd
+cd "${buildfolder}"
+if ! cmake "${drv_dir}" ${options}; then
+  echo "Error preparing environment!"
+elif ! make clean; then
+  echo "Error clean up library libcifx!"
+elif ! make ; then
+  echo "Error building user space library libcifx!"
+else
+  if ! sudo make install; then
+    echo "Error installing userspace driver!"
   else
-    options="$options -DSPM_PLUGIN=OFF"
+    echo "cifX driver successfully installed!"
   fi
-  tmp_dir=$pwd
-  cd "${buildfolder}"
-  if ! cmake "${drv_dir}" ${options}; then
-    echo "Error preparing environment!"
-  elif ! make clean; then
-    echo "Error clean up library libcifx!"
-  elif ! make ; then
-    echo "Error building user space library libcifx!"
-  else
-    if ! sudo make install; then
-      echo "Error installing userspace driver!"
-    else
-      echo "cifX driver successfully installed!"
-    fi
-  fi
-  cd "${tmp_dir}"
+fi
+cd "${tmp_dir}"
